spring:
  main:
    banner-mode: off
  jpa:
    open-in-view: false
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: axgr
    password: swordfish
  data:
    web:
      pageable:
        default-page-size: 10
